version: "2.1"
services:
  nginx:
    # Note : Only nginx:alpine supports bcrypt.
    # If you don't need to use bcrypt, you can use a different tag.
    # Ref. https://github.com/nginxinc/docker-nginx/issues/29
    image: "nginx:alpine"
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
    links:
      - registry:registry
    volumes:
      - ./auth:/etc/nginx/conf.d
      - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro
      - $HOME/data/certbot/conf:/etc/letsencrypt
      - $HOME/data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 120h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - $HOME/data/certbot/conf:/etc/letsencrypt
      - $HOME/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 240h & wait $${!}; done;'"
  
  registry:
    image: registry:2
    restart: unless-stopped
    container_name: registry
    volumes:
      - $HOME/data/registry:/var/lib/registry
      - ./config-example.yml:/etc/docker/registry/config.yml 
  
  ui:
    image: joxit/docker-registry-ui:static
    restart: unless-stopped
    container_name: ui_registry
    ports:
      - 8088:80
    environment:
      - REGISTRY_TITLE=POORDEV Private Docker Registry
      - REGISTRY_URL=http://registry:5000
      - PULL_URL=https://poordev.ddns.net:5043
      - DELETE_IMAGES=true
    depends_on:
      - registry